#!/usr/bin/env python3
"""
Multi-Agent Business Assistant — Complete Google Calendar API Feature Testing Suite
Tests Calendar operations (list events, find availability, create test meeting, delete test meeting).
"""

import os
import sys
import datetime
from google.oauth2.credentials import Credentials
from google_auth_oauthlib.flow import InstalledAppFlow
from googleapiclient.discovery import build
from google.auth.transport.requests import Request

SCOPES = [
    'https://www.googleapis.com/auth/gmail.modify',
    'https://www.googleapis.com/auth/gmail.send',
    'https://www.googleapis.com/auth/gmail.compose',
    'https://www.googleapis.com/auth/gmail.readonly',
    'https://www.googleapis.com/auth/calendar'
]

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
CREDENTIALS_FILE = os.path.join(BASE_DIR, "credentials", "credentials.json")
TOKEN_FILE = os.path.join(BASE_DIR, "credentials", "token.json")

def print_header(title):
    print("\n" + "="*70)
    print(f" 📅 {title}")
    print("="*70)

def get_calendar_service():
    print_header("STEP 1: Authenticating with Google OAuth2 for Calendar")
    creds = None
    if os.path.exists(TOKEN_FILE):
        print(f"📁 Found saved token at {TOKEN_FILE}. Loading credentials...")
        creds = Credentials.from_authorized_user_file(TOKEN_FILE, SCOPES)
    
    if not creds or not creds.valid:
        if creds and creds.expired and creds.refresh_token:
            print("🔄 Refreshing expired token...")
            creds.refresh(Request())
        else:
            if not os.path.exists(CREDENTIALS_FILE):
                print(f"❌ Error: Credentials file not found at {CREDENTIALS_FILE}")
                sys.exit(1)
            
            print("🌐 Launching local OAuth browser for initial authentication...")
            flow = InstalledAppFlow.from_client_secrets_file(CREDENTIALS_FILE, SCOPES)
            creds = flow.run_local_server(port=0)
            
        os.makedirs(os.path.dirname(TOKEN_FILE), exist_ok=True)
        with open(TOKEN_FILE, 'w') as token:
            token.write(creds.to_json())
            print(f"✅ Token successfully saved to {TOKEN_FILE}")

    service = build("calendar", "v3", credentials=creds)
    print("✅ Calendar Service built successfully!")
    return service

def test_list_upcoming_events(service):
    print_header("STEP 2: Testing Read — Fetching Upcoming 5 Events")
    now = datetime.datetime.utcnow().isoformat() + 'Z'  # 'Z' indicates UTC time
    events_result = service.events().list(
        calendarId='primary', timeMin=now,
        maxResults=5, singleEvents=True,
        orderBy='startTime').execute()
    events = events_result.get('items', [])

    if not events:
        print("📭 No upcoming events found.")
    else:
        for i, event in enumerate(events, 1):
            start = event['start'].get('dateTime', event['start'].get('date'))
            print(f" [{i}] {start} -> {event['summary']}")
    print("✅ Calendar Read testing complete!")

def test_create_and_delete_meeting(service):
    print_header("STEP 3: Testing Create Meeting & Delete Meeting")
    # Schedule a test meeting 1 hour from now for 30 mins
    now = datetime.datetime.now()
    start_time = (now + datetime.timedelta(hours=1)).isoformat() + 'Z'
    end_time = (now + datetime.timedelta(hours=1, minutes=30)).isoformat() + 'Z'
    
    event_body = {
        'summary': 'AI Assistant: Strategic Review Test Meeting 🤝',
        'location': 'Online Video Call / LangGraph HQ',
        'description': 'Automated meeting verification generated by the Multi-Agent Business Assistant.',
        'start': {'dateTime': start_time, 'timeZone': 'UTC'},
        'end': {'dateTime': end_time, 'timeZone': 'UTC'},
    }
    
    print("⏰ Creating test meeting in your primary calendar...")
    event = service.events().insert(calendarId='primary', body=event_body).execute()
    event_id = event['id']
    print(f"🎉 Meeting created successfully! Event link: {event.get('htmlLink')}")
    
    print(f"🗑️ Now cleaning up: Deleting test event (ID: {event_id})...")
    service.events().delete(calendarId='primary', eventId=event_id).execute()
    print("✅ Test Event deleted cleanly from your calendar!")

def main():
    print_header("STARTING GOOGLE CALENDAR API TEST SUITE")
    service = get_calendar_service()
    test_list_upcoming_events(service)
    test_create_and_delete_meeting(service)
    print_header("🎉 GOOGLE CALENDAR API FULLY VERIFIED! 🎉")

if __name__ == '__main__':
    main()
