import os
from loguru import logger
from backend.app.tools.pdf_generator import PDFGeneratorTool
from backend.app.tools.docx_generator import DocxGeneratorTool

class ContentWriterAgent:
    def run(self, instruction: str) -> str:
        logger.info(f"✍️ CONTENT WRITER AGENT building document asset: '{instruction}'")
        title = "Executive Multi-Agent Strategy Briefing"
        content = f"Document generated by Content Writer Agent based on instructions: {instruction}\n\nKey Highlights:\n1. Autonomous Task Orchestration\n2. Real-time RAG Knowledge Integration\n3. Scalable Relational Architecture."
        
        pdf_path = PDFGeneratorTool.create_report("executive_briefing.pdf", title, content)
        docx_path = DocxGeneratorTool.create_document("executive_briefing.docx", title, content)
        
        return f"[Content Writer Agent] Created professional document reports successfully:\n- PDF: {pdf_path}\n- DOCX: {docx_path}"

content_writer_agent = ContentWriterAgent()
